
name: bullstudio-dev-services
services:
  postgres:
    image: postgres:16
    container_name: bullstudio_postgres
    restart: always
    environment:
      - POSTGRES_USER=bullstudio_user
      - POSTGRES_PASSWORD=bullstudio_password
      - POSTGRES_DB=bullstudio_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: bullstudio_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--maxmemory-policy", "noeviction"]


volumes:
  database:
  redis_data:
