# For development purposes only

services:
  postgres:
    image: postgres:16
    container_name: pg-bullstudio-dev
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: bullstudio
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5455:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data_new
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: