
name: bullstudio-prod-services

services:
  postgres:
    image: postgres:16
    container_name: bullstudio_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: bullstudio_redis
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--maxmemory-policy", "noeviction"]


volumes:
  database:
  redis_data:
